@startuml
!pragma layout smetana

class Streamingservice {
  +users: List<user>
  + movies: List<Movie>
  + series : List<Series>
  +displaystartmenu(): void
  +displayMainMenu(User user): void
  +Searchmovie(String Title): Movie
  + Searchmoviefromcategory(String category): Movie
  +playmovie(String movie) void
  +RemoveMovie(User user, Movie movie):void
  +savelogininfo(User user):void
}

class User {
    -String username
    -String password
    +watchedMovies: List<Movie>
    +savedMovies:List<Movie>
}

class Series {
    -int Seasons
    -int startyear
    -int endyear
}

class Season {
    -Int seasonNumber
    -int Episodes
}

class Episode {
-int length
}


class Fileio {
}

abstract class Media{
- String title
- String category
-int Rating
}

class TextUI {
+ void Displaymessage(String msg)
+DisplayWatchedmovie(User user): List<Movie>
 +DisplaySavedmovie(User user): List<Movie>
 +DisplayWatchedseries(Series series) List<Series>
+DisplaySavedseries(User user): List<Series>
}

class Movie {
-int year
}

interface Filebase{
+ArrayList<String> readMovieData(String path)
+ public void saveMovieData(ArrayList<Movie> movies)
}



Streamingservice *-- Filebase
Streamingservice o--  TextUI
Streamingservice o-- User
Streamingservice *-- Media
Filebase o-- Fileio
Media *-- Series
Media *-- Movie
Series *-- Season
Episode --* Season




@enduml
